language: java

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./setup_openfire.sh

script: ./gradlew clean build endtoendTest --info

jdk:
  - oraclejdk8

env:
  - TERM=dumb

deploy:
  provider: heroku
  api_key:
    secure: "Nm/3kMxyprL8KX2mUipdM/crJV3JoAZb9m/18+mUDuzlvI4h6wK1NpyJwVs31/07sCSRijR01LB7KKR86gbUSyEGC/VJeRW/DI1p3Bs/Ikt1Lr8UpJ24+ihlBKxPrOIa9UFphkjLPFtAIjvZqqKUrEcWYVRmA+VuanqiE/NcImFtXIQStxyIrfyuzJXxE4SQ/Vba1xcoSJG5TsLHwTVGuQhTgtfgWd3cegJv/Tn/FDTcntVToZe50df2OeHjU5uXkjRijNsNean1naF6x67Qw3CtFltqE/yvOJccxWrUQ5M0a2pXxfPHbI/n7IfHceEsBEs9gMkQcpjBk2uZ/7gz/pcYvtvB5iyFEY0L34RHK1Nxso6mIcxFGoIsx1GNpWOuKMVyqLeQmzra7oPUHHN0c1hWLbGqqmnnioQLCD5sgXZYBupfPIGhTFujznrzT0aLnutTL3UedR0ppNqSD3A3uFSryQ6lvqf/JL2KlhRl9V0SKy7VuBVC/eqVEv5GNWCn5R0oPjYb1bCsLYkJc0udoYkmQhoVKuiDMmAizBebZ9ZRIQx06z+taZujbrlRU28o5pMKi2RA/PiV0TkEvRNtXAhhY/RIRdMFAlbdAUzwDmCWCBXMqbcpAL8t2D0HW0If5aJaI4qBozzeFGTZ0LlyXlEcfwl4unNyKZWfjG+Nsg0="

after_success:
  - ./gradlew jacocoEndtoendTestReport coveralls --info

after_script:
  - kill $(cat server/openfire.pid)
